/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BantuanRouteImport } from './routes/bantuan'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InfoRouteImport } from './routes/info'
import { Route as KartuStokRouteImport } from './routes/kartu-stok'
import { Route as KaryawanRouteImport } from './routes/karyawan'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PenjualanHarianRouteImport } from './routes/penjualan-harian'
import { Route as PinRouteImport } from './routes/pin'
import { Route as PiutangRouteImport } from './routes/piutang'
import { Route as SpreadsheetRouteImport } from './routes/spreadsheet'
import { Route as StokRouteImport } from './routes/stok'
import { Route as UtangRouteImport } from './routes/utang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BantuanRoute = BantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const KartuStokRoute = KartuStokRouteImport.update({
  id: '/kartu-stok',
  path: '/kartu-stok',
  getParentRoute: () => rootRouteImport,
} as any)
const KaryawanRoute = KaryawanRouteImport.update({
  id: '/karyawan',
  path: '/karyawan',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualanHarianRoute = PenjualanHarianRouteImport.update({
  id: '/penjualan-harian',
  path: '/penjualan-harian',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const PiutangRoute = PiutangRouteImport.update({
  id: '/piutang',
  path: '/piutang',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsheetRoute = SpreadsheetRouteImport.update({
  id: '/spreadsheet',
  path: '/spreadsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const StokRoute = StokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => rootRouteImport,
} as any)
const UtangRoute = UtangRouteImport.update({
  id: '/utang',
  path: '/utang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bantuan': typeof BantuanRoute
  '/dashboard': typeof DashboardRoute
  '/info': typeof InfoRoute
  '/kartu-stok': typeof KartuStokRoute
  '/karyawan': typeof KaryawanRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/penjualan-harian': typeof PenjualanHarianRoute
  '/pin': typeof PinRoute
  '/piutang': typeof PiutangRoute
  '/spreadsheet': typeof SpreadsheetRoute
  '/stok': typeof StokRoute
  '/utang': typeof UtangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bantuan': typeof BantuanRoute
  '/dashboard': typeof DashboardRoute
  '/info': typeof InfoRoute
  '/kartu-stok': typeof KartuStokRoute
  '/karyawan': typeof KaryawanRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/penjualan-harian': typeof PenjualanHarianRoute
  '/pin': typeof PinRoute
  '/piutang': typeof PiutangRoute
  '/spreadsheet': typeof SpreadsheetRoute
  '/stok': typeof StokRoute
  '/utang': typeof UtangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bantuan': typeof BantuanRoute
  '/dashboard': typeof DashboardRoute
  '/info': typeof InfoRoute
  '/kartu-stok': typeof KartuStokRoute
  '/karyawan': typeof KaryawanRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/penjualan-harian': typeof PenjualanHarianRoute
  '/pin': typeof PinRoute
  '/piutang': typeof PiutangRoute
  '/spreadsheet': typeof SpreadsheetRoute
  '/stok': typeof StokRoute
  '/utang': typeof UtangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bantuan'
    | '/dashboard'
    | '/info'
    | '/kartu-stok'
    | '/karyawan'
    | '/laporan'
    | '/login'
    | '/pengaturan'
    | '/penjualan-harian'
    | '/pin'
    | '/piutang'
    | '/spreadsheet'
    | '/stok'
    | '/utang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bantuan'
    | '/dashboard'
    | '/info'
    | '/kartu-stok'
    | '/karyawan'
    | '/laporan'
    | '/login'
    | '/pengaturan'
    | '/penjualan-harian'
    | '/pin'
    | '/piutang'
    | '/spreadsheet'
    | '/stok'
    | '/utang'
  id:
    | '__root__'
    | '/'
    | '/bantuan'
    | '/dashboard'
    | '/info'
    | '/kartu-stok'
    | '/karyawan'
    | '/laporan'
    | '/login'
    | '/pengaturan'
    | '/penjualan-harian'
    | '/pin'
    | '/piutang'
    | '/spreadsheet'
    | '/stok'
    | '/utang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BantuanRoute: typeof BantuanRoute
  DashboardRoute: typeof DashboardRoute
  InfoRoute: typeof InfoRoute
  KartuStokRoute: typeof KartuStokRoute
  KaryawanRoute: typeof KaryawanRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  PengaturanRoute: typeof PengaturanRoute
  PenjualanHarianRoute: typeof PenjualanHarianRoute
  PinRoute: typeof PinRoute
  PiutangRoute: typeof PiutangRoute
  SpreadsheetRoute: typeof SpreadsheetRoute
  StokRoute: typeof StokRoute
  UtangRoute: typeof UtangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantuan': {
      id: '/bantuan'
      path: '/bantuan'
      fullPath: '/bantuan'
      preLoaderRoute: typeof BantuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kartu-stok': {
      id: '/kartu-stok'
      path: '/kartu-stok'
      fullPath: '/kartu-stok'
      preLoaderRoute: typeof KartuStokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karyawan': {
      id: '/karyawan'
      path: '/karyawan'
      fullPath: '/karyawan'
      preLoaderRoute: typeof KaryawanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjualan-harian': {
      id: '/penjualan-harian'
      path: '/penjualan-harian'
      fullPath: '/penjualan-harian'
      preLoaderRoute: typeof PenjualanHarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piutang': {
      id: '/piutang'
      path: '/piutang'
      fullPath: '/piutang'
      preLoaderRoute: typeof PiutangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreadsheet': {
      id: '/spreadsheet'
      path: '/spreadsheet'
      fullPath: '/spreadsheet'
      preLoaderRoute: typeof SpreadsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stok': {
      id: '/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof StokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utang': {
      id: '/utang'
      path: '/utang'
      fullPath: '/utang'
      preLoaderRoute: typeof UtangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BantuanRoute: BantuanRoute,
  DashboardRoute: DashboardRoute,
  InfoRoute: InfoRoute,
  KartuStokRoute: KartuStokRoute,
  KaryawanRoute: KaryawanRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  PengaturanRoute: PengaturanRoute,
  PenjualanHarianRoute: PenjualanHarianRoute,
  PinRoute: PinRoute,
  PiutangRoute: PiutangRoute,
  SpreadsheetRoute: SpreadsheetRoute,
  StokRoute: StokRoute,
  UtangRoute: UtangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
